config/routes.rb
Rails.application.routes.draw do
  #get 'users/new'
  root 'articles#all'
  resources :users do
  	resources :articles
  end
 #    resources :articles do
	#   resources :comments
	# end
  resources :sessions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user
	validates :title, presence: true,
	                  length: { maximum: 50 }
	validates :text,  presence: true
end

app/models/user.rb
class User < ApplicationRecord
	has_many :articles, -> { order(created_at: :desc) }, dependent: :destroy
	has_secure_password

	email_regex = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i

	validates :name,				 :presence 	=> true,
						:length										=> {:maximum => 50}
	validates :email,				 :presence	=> true,
						:format										=> {:with => email_regex},
						:uniqueness								=> {:case_sensitive => false}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :deny__access, :except => [:all]

  def all
    if signed_in?
      @user = current_user
    end
    @articles = Article.order('created_at DESC').page(params[:page]).per_page(10)

  end

  def index
    @user = User.find(params[:user_id])
    @articles = Article.where('user_id = ?',  @user.id).order('created_at DESC').page(params[:page]).per_page(10)
    @article = @user.articles.build
    render :action => 'index'
  end

  def show
    @user = User.find(params[:user_id])
    @article = @user.articles.find(params[:id])
    render :action => 'show'
  end

  def new
  end

  def edit
    @user = User.find(params[:user_id])
    @articles = Article.where('user_id = ?',  @user.id).order('created_at DESC').page(params[:page]).per_page(10)
    @article = @user.articles.find(params[:id])
    render :action => 'index'
  end

  def update
    @user = User.find(params[:user_id])
    @articles = Article.where('user_id = ?',  @user.id).order('created_at DESC').page(params[:page]).per_page(10)
    @article = Article.find(params[:id])
    if  @article.update_attributes(article_params)
      redirect_to user_articles_path(@user)
    else
      render :action => 'index'
    end
  end

  def create
    @user = User.find(params[:user_id])
    @articles = Article.where('user_id = ?',  @user.id).order('created_at DESC').page(params[:page]).per_page(10)
    @article = @user.articles.create(article_params)
    if @article.errors.any?
      render :action => 'index'
    else
      redirect_to user_articles_path(@user)
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @article = @user.articles.find(params[:id])
    @article.destroy
    redirect_to user_articles_path(@user)
  end

  private
    def article_params
      params.require(:article).permit(:title, :text)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		if signed_in?
			redirect_to user_articles_path(current_user)
		end
	end

	def create
		user = User.find_by_email(params[:session][:email])
	  if user && user.authenticate(params[:session][:password])
			sign_in user
			redirect_to user_articles_path(user)
		else
			flash.now[:error] = "Invalid email/password combination."
			render :action => 'new'
		end
	end

	def destroy
		sign_out
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  	@user = User.new
  end

  def create
    @user = User.new(user_params)
    if User.exists?(:email => user_params[:email])
      flash.now[:notice] = "User email already taken."
      render action: 'new'
    else
    	if @user.save
        redirect_to new_session_path(), notice: 'User was successfully created, You can now login.'
  		else
  			render action: "new"
  		end
    end	
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(email, size= 100)
  	gravatar = Digest::MD5::hexdigest(email).downcase
    url = "http://gravatar.com/avatar/#{gravatar}.png?s=#{size}"
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
		session[:user_id] = user.id
		self.current_user = user
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def signed_in?
		!current_user.nil?
	end

	def sign_out
		session[:user_id] = nil
		self.current_user = nil
	end

	def current_user?(user)
		user == current_user
	end

	def deny__access
		redirect_to new_session_path,	:alert => "Please sign in to access the page." unless signed_in?
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/all.html.erb
<div class="container">
	<div class="row pad-bottom-50">
		<div class="col-sm-3"></div>
		<div class="col-sm-7">
				<div class="row">
					<div class="col-sm-12">
						<h2>Articles</h2>
						<% if !@articles.empty? %>
							<% @articles.each do |article| %>
								<div class="pad-top-bottom-10">
								  <p>
								    <strong>Title:</strong>
								    <%= article.title %>
								  </p>
								  <p>
								    <strong>Content:</strong>
								    <%= truncate(article.text, length: 250, omission: "... %s") % link_to('Read more', user_article_path(article.user_id, article.id)) %>
								  </p>
								  <h5 class="list-group-item-headingclass post-info "> 
										<%= article.created_at.strftime("%d %b %y") %>
										<span class="author-name">
											<%= link_to article.user.name, user_articles_path(article.user_id) %>
										</span>
									</h5>
								  <% if @user && @user.id == article.user_id %>
									  <p>
											<%= link_to 'Edit', edit_user_article_path(@user, article) %>
											<%= link_to 'Delete', [article.user, article],
						              method: :delete,
						              data: { confirm: 'Are you sure?' } %>
									  </p>
								  <% end %>
								</div>
							<% end %>
							<%= will_paginate @articles, renderer: BootstrapPagination::Rails %>
					  <% else %>
								<div class="main-post-container">
									<div class="list-group-item">
										<p>Unfortunately, there are no articles to show.</p>
									</div>
								</div>
						<% end %>
					</div>
				</div>
		</div>
		<div class="col-sm-2"></div>
	</div>
</div>

app/views/articles/index.html.erb
<div class="container">
	<div class="row pad-bottom-50">
		<div class="col-sm-3">
			<%= image_tag avatar_url(@user.email, 150), :class => 'img-thumbnail' %>
			<h3><%= @user.name %></h3>
			<p><%= @user.email %></p>
		</div>
		<div class="col-sm-7">
			<% if current_user? @user %>
				<div class="row">
					<div class="col-sm-12">
						<%= simple_form_for([@user, @article]) do |f| %>
						  <p>
						    <%= f.input :title %>
						  </p>
						  <p>
						    <%= f.input :text, :input_html => { :rows => 5 }%>
						  </p>
						  <p>
						    <%= f.button :submit, :class => 'btn btn-success' %>
						  </p>
						<% end %>
					</div>
				</div>
			<% end %>

			<div class="row">
				<div class="col-sm-12">
					<h2>Articles</h2>
					<% if !@articles.empty? %>
						<% @articles.each do |article| %>
							<div class="pad-top-bottom-10">
							  <p>
							    <strong>Title:</strong>
							    <%= article.title %>
							  </p>
							  <p>
							    <strong>Content:</strong>
							    <%= truncate(article.text, length: 250, omission: "... %s") % link_to('Read more', user_article_path(article.user_id, article.id)) %>
							  </p>
							  <h5 class="list-group-item-headingclass post-info "> 
									<%= article.created_at.strftime("%d %b %y") %>
									<span class="author-name"><%= article.user.name %></span>
								</h5>
								<% if current_user? @user %>
								  <p>
										<%= link_to 'Edit', edit_user_article_path(@user, article) %>
										<%= link_to 'Delete', [article.user, article],
					              method: :delete,
					              data: { confirm: 'Are you sure?' } %>
								  </p>
						  	<% end %>
						  </div>
						<% end %>
						<%= will_paginate @articles, renderer: BootstrapPagination::Rails %>
				  <% else %>
						<div class="main-post-container">
							<div class="list-group-item">
								<p>Unfortunately, there are no articles to show.</p>
							</div>
						</div>
				  <% end %>
				</div>
			</div>
		</div>
		<div class="col-sm-2"></div>
	</div>
</div>

app/views/articles/show.html.erb
<div class="container">
	<div class="row pad-bottom-50">
		<div class="col-sm-3">
			<%= image_tag avatar_url(@user.email, 150), :class => 'img-thumbnail' %>
			<h3><%= @user.name %></h3>
			<p><%= @user.email %></p>
		</div>
		<div class="col-sm-7">
			<div class="row">
				<div class="col-sm-12">
					<h2>Articles</h2>
					<div class="pad-top-bottom-10">
					  <p>
					    <strong>Title:</strong>
					    <%= @article.title %>
					  </p>
					  <p>
					    <strong>Content:</strong>
					    <%= @article.text %>
					  </p>
					  <h5 class="list-group-item-headingclass post-info "> 
							<%= @article.created_at.strftime("%d %b %y") %>
							<span class="author-name"><%= @article.user.name %></span>
						</h5>
						<% if current_user? @user %>
						  <p>
								<%= link_to 'Edit', edit_user_article_path(@user, @article) %>
								<%= link_to 'Delete', [@article.user, @article],
			              method: :delete,
			              data: { confirm: 'Are you sure?' } %>
						  </p>
				  	<% end %>
				  </div>
				</div>
			</div>
		</div>
		<div class="col-sm-2"></div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LoginSignup</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
    <body>
      <div id="structure-container">
        <div id="header-container">
          <nav class="navbar navbar-default">
            <div class="container-fluid">
              <!-- Brand and toggle get grouped for better mobile display -->
              <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <span class="navbar-brand">Jed Blog</span>
              </div>

              <!-- Collect the nav links, forms, and other content for toggling -->
              <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                  <li><%= link_to 'Home', root_path %></li>
                  <% if signed_in? %>
                    <li><%= link_to 'Profile', user_articles_path(@current_user) %></li>
                  <% end %>
                </ul>
                <% if signed_in? %>
                  <ul class="nav navbar-nav navbar-right">
                    <li>
                      <%= link_to 'Log Out', session_path(@current_user),
                        method: :delete,
                        data: { confirm: 'Are you sure?' } %>
                    </li>
  <!--                   <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                      <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Separated link</a></li>
                      </ul>
                    </li> -->
                  </ul>
                  <p class="navbar-text navbar-right">
                    <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                    Signed in as <%= link_to @current_user.name, user_articles_path(@current_user) %>
                  </p>
                <% else %>
                  <ul class="nav navbar-nav navbar-right">
                    <li><%= link_to 'Register', new_user_path %></li>
                    <li><%= link_to 'Login', new_session_path %></li>
                  </ul>
                <% end %>
              </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
          </nav>
      </div>

      <div id="content-container">
        <%= yield %>
      </div>

      <div id ="footer-container">
        <div class="container">
          <div class="row">
            <div class="col-sm-12 text-center">
              <h6>© 2016 Copyright Jedidiah Blog | Powered by <a href="http://jedidiah-portfolio.herokuapp.com/" target="_blank">jedidiah-portfolio</a></h6>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/users/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-4"></div>
		<div class="col-sm-4">
			<h1>Users Registration</h1>
			<% if flash[:notice] %>
				<div class="alert alert-danger">
				  <strong>Alert:</strong><%= flash[:notice] %>
				</div>
			<% end %>
			<%= simple_form_for(@user) do |f| %>
				<%= f.input :name %>
				<%= f.input :email %>
				<%= f.input :password %>
				<%= f.input :password_confirmation %>
				<%= f.button :submit, :class => 'pull-left' %>
			<% end %>
			<p><%= link_to 'Login', new_session_path,
	      		:class => 'btn btn-default pull-right'  %>
			</p>
			<div class="clear"></div>
		</div>
		<div class="col-sm-4"></div>
	</div>
</div>